name = "mcp-logging-webhook"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[vars]
# Non-secret config
BIGQUERY_DATASET = "hiring_router_mcp"
BIGQUERY_TABLE = "logging_events"

# BIGQUERY_PROJECT_ID should be set either here or as a secret/var per environment
# BIGQUERY_PROJECT_ID = "your-project-id"

# Secrets to set via `wrangler secret put`:
# - WEBHOOK_SECRET (optional)
# - GCP_CLIENT_EMAIL
# - GCP_PRIVATE_KEY


